spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studycafe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root      # 본인 ID
    password: ${DB_PASSWORD}      # 본인 PW
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 테이블이 없으면 생성, 있으면 변경사항만 반영
    properties:
      hibernate:
        format_sql: true # 로그에 SQL 예쁘게 출력
        show_sql: true   # 로그에 SQL 출력
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8.0 최적화 방언 설정 (권장)

  # Redis 설정 (Step 1 의존성 관련)
  data:
    redis:
      host: localhost
      port: 6379